import { allWindows } from '@src/lib/dom';

export interface SafeFrameWindow extends Window {
  // $sf would be set when it locates in a safeframe container
  // https://www.iab.com/guidelines/safeframe/
  $sf: SafeFrame;
}

export interface SafeFrame {
  ext: SafeFrameExt;
}

type SafeFrameEvent = 'geom-update';

// SafeFrameExt is the extension set which we supports.
// For Google GPT, only a subset of IAB SafeFrame extension is supported.
// @see https://support.google.com/admanager/answer/6023110?hl=en
interface SafeFrameExt {
  inViewPercentage: () => number;
  winHasFocus: () => boolean;
  register: (
    w: number,
    h: number,
    callback: (status: SafeFrameEvent, data: unknown) => void
  ) => void;
  geom: () => Geom;
  expand: (conf: ExpandConfig) => void;
  collapse: () => void;
}

interface ExpandConfig {
  t: number;
  r: number;
  b: number;
  l: number;
  push: boolean;
}

// Generated by https://quicktype.io
interface Geom {
  win: GeomWin;
  self: GeomSelf;
  exp: GeomExp;
}

export interface GeomExp {
  t: number;
  r: number;
  b: number;
  l: number;
  xs: boolean;
  yx: boolean;
}

export interface GeomSelf {
  t: number;
  r: number;
  b: number;
  l: number;
  w: number;
  h: number;
  z: null;
  xiv: number;
  yiv: number;
  iv: number;
}

export interface GeomWin {
  t: number;
  r: number;
  b: number;
  l: number;
  w: number;
  h: number;
}

export const isSafeFrameWindow = (
  v: Window | undefined
): v is SafeFrameWindow => {
  const w = v as SafeFrameWindow;
  return w?.$sf?.ext?.inViewPercentage !== undefined;
};

export const getNearestSafeFrame = (): SafeFrame | undefined => {
  const wIter = allWindows();
  let n = 10;
  let w: Window | void | null = null;
  do {
    try {
      w = wIter.shift();
      if (w && isSafeFrameWindow(w)) {
        return w.$sf;
      }
    } catch (err) {} // this error is acceptable
  } while (w && --n);
  return undefined;
};
